---
version: '2'
services:
  metaphysics:
    extends:
      file: common.yml
      service: metaphysics
    environment:
    - NODE_ENV=development
    - MEMCACHE_SERVERS=metaphysics-memcached:11211
    - ENABLE_QUERY_TRACING=false
    - DEBUG=info,error
    - PORT=5001
    env_file: ../.env
    command: node_modules/.bin/babel-node --inspect index.js
    ports:
    - 5001:5001
    depends_on:
    - metaphysics-memcached
  metaphysics-memcached:
    image: memcached
    ports:
    - 11211:11211
