---
version: '2'
services:
  metaphysics:
    command: yarn test
    extends:
      file: common.yml
      service: metaphysics
    environment:
    - MEMCACHED_URL=metaphysics-memcached:11211
    env_file: ../.env.test
    depends_on:
    - metaphysics-redis
  metaphysics-memcached:
    image: memcached
    ports:
    - 11211:11211
